CREATE DATABASE IF NOT EXISTS MOVIES;
USE MOVIES;

CREATE USER IF NOT EXISTS 'MOVIE_USER'@'localhost' IDENTIFIED BY 'MOVIE_USER';
GRANT ALL PRIVILEGES ON MOVIES.* TO 'MOVIE_USER'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS USERS(
    id integer unique not null ,
    name VARCHAR(255),
    PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS GENRES (
    id int NOT NULL AUTO_INCREMENT,
    genre varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USER_GENRE(
    user_id int NOT NULL,
    genre_id int NOT NULL,
    PRIMARY KEY (user_id, genre_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (genre_id) REFERENCES GENRES(id)
);